spring:
  application:
    name: realworld
  datasource:
    url: jdbc:postgresql://192.168.248.32:5432/realworld
    username: dev_account
    password: d784512d
server:
  port: 8081
  servlet:
    context-path: /api